language: python

stages:
  - test

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"

install:
  - pip install poetry
  - poetry install -v

script: pytest -q tests/

jobs:
  include:
    - python: "3.6"
    - python: "3.7"
      dist: xenial

notifications:
  email: false
