language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
  - "pypy"
install: 
  - pip install codecov
  - pip install -r requirements-test.txt
script:
  - coverage run -m unittest discover
  - coverage report -m
after_success:
  - coveralls
  - codecov
