language: python
sudo: false
cache: pip
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
install: 
  - pip install -r requirements-dev.txt
script:
  - coverage run -m unittest discover
  - coverage report -m
after_success:
  - coveralls
  - codecov
